name: Testes e Cobertura

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Backend
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test and collect coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: '**/coverage.cobertura.xml'
        flags: unittests
        name: codecov-coverage

    #Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install Playwright dependencies
      working-directory: ./notas.e2eTests
      run: npm ci

    - name: Install frontend dependencies
      working-directory: ./notas.client
      run: npm ci

    - name: Build frontend
      working-directory: ./notas.client
      run: npm run build

    - name: Install Playwright Browsers
      working-directory: ./notas.e2eTests
      run: |
        npx playwright install --with-deps
        ls -la ~/.cache/ms-playwright || echo "Playwright cache não encontrado"

    - name: Run Playwright tests
      working-directory: ./notas.e2eTests
      run: npx playwright test --reporter=html

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ./notas.e2eTests/playwright-report
